---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: quicksilver-examples
  description: DevX owned repository
spec:
  type: service
  lifecycle: production
  owner: developer-experience
